version: '3.8'

services:
  flask-app1:
    env_file:
      - .env
    build:
      context: ./ai-model/app1
      dockerfile: Dockerfile
    container_name: flask-app1
    ports:
      - "5050:5000"
    volumes:
      - ./ai-model/app1:/app
      - whisper-cache:/root/.cache/whisper
    environment:
      - FLASK_ENV=development

  flask-app2:
    env_file:
      - .env
    build:
      context: ./ai-model/app2
      dockerfile: Dockerfile
    container_name: flask-app2
    ports:
      - "5051:5001"
    volumes:
      - ./ai-model/app2:/app
      - whisper-cache:/root/.cache/whisper
    environment:
      - FLASK_ENV=development

  flask-app4:
    env_file:
      - .env
    build:
      context: ./ai-model/app4
      dockerfile: Dockerfile
    container_name: flask-app4
    ports:
      - "5052:5002"
    volumes:
      - ./ai-model/app4:/app
      - whisper-cache:/root/.cache/whisper
      - ./ai-model/app4/model4.pkl:/app/model4.pkl
    environment:
      - FLASK_ENV=development

  next-app:
    env_file:
      - .env
    build:
      context: ./web-app
      dockerfile: Dockerfile.next
    container_name: next-app
    ports:
      - "3000:3000"
    volumes:
      - ./web-app:/app
      - /app/node_modules
      - ./web-app/.env:/app/.env 
    environment:
      - NODE_ENV=development
    depends_on:
      - flask-app1
      - flask-app2
      - flask-app4

volumes:
  whisper-cache:
