services:
  - type: web
    name: flask-app1
    env: docker
    repo: https://github.com/abhijeetmishra2104/SonicScribe
    dockerfilePath: ai-model/app1/Dockerfile
    plan: free
    region: singapore
    buildFilter:
      paths:
        - ai-model/app1/**
    envVars:
      - key: FLASK_ENV
        value: development
    autoDeploy: true

  - type: web
    name: flask-app2
    env: docker
    repo: https://github.com/abhijeetmishra2104/SonicScribe
    dockerfilePath: ai-model/app2/Dockerfile
    plan: free
    region: singapore
    buildFilter:
      paths:
        - ai-model/app2/**
    envVars:
      - key: FLASK_ENV
        value: development
    autoDeploy: true

  - type: web
    name: flask-app4
    env: docker
    repo: https://github.com/abhijeetmishra2104/SonicScribe
    dockerfilePath: ai-model/app4/Dockerfile
    plan: free
    region: singapore
    buildFilter:
      paths:
        - ai-model/app4/**
    envVars:
      - key: FLASK_ENV
        value: development
    autoDeploy: true
